
[[frasi.branco]]
text = "La forza del branco è nel lupo, la forza del lupo è nel branco"
[[frasi.branco]]
text = "Sii pulito perché la forza del cacciatore si riconosce dalla lucentezza del suo pelo"
[[frasi.branco]]
text = "La tana del lupo è la sua casa e rifugio: custodiscila con cura e aprila agli amici"
[[frasi.branco]]
text = "Prima di metterti in caccia osserva bene il territorio"
[[frasi.branco]]
text = "Quando cambi territorio, chiedi il permesso di cacciare per non rovinare la caccia ai tuoi fratelli"
[[frasi.branco]]
text = "Come la liana cinge il tronco dell'albero così la legge corre avanti e indietro"
[[frasi.branco]]
text = "Siamo tutti sotto una stessa legge"
[[frasi.branco]]
text = "Il diritto del branco è il diritto del più debole"
[[frasi.branco]]
text = "La tua traccia è la mia traccia, la tua preda è la mia preda, la tua tana è la mia tana"

[[frasi.cerchio]]
text = "Se qualcosa viene smarrito cercando è sempre possibile ritrovarlo!"
[[frasi.cerchio]]
text = "Non saresti mai felice se non decidessi di continuare"
[[frasi.cerchio]]
text = "Dimmi cosa posso fare per te e lo farò volentieri"
[[frasi.cerchio]]
text = "Quello che i miei occhi possono vedere non è quello che possono vedere i vostri"
[[frasi.cerchio]]
text = "A ciascuno è chiesto in misura a quello che gli è stato assegnato di dare"
[[frasi.cerchio]]
text = "Dai buttati anche tu!"
[[frasi.cerchio]]
text = "Ti devo la gioia di averti potuto aiutare"
[[frasi.cerchio]]
text = "Il Bosco è il grande abbraccio degli alberi"
[[frasi.cerchio]]
text = "(Ughetto) cominciava sempre la sua giornata con una risata"
[[frasi.cerchio]]
text = "Il cielo continua ad essere azzurro anche quando piove"
[[frasi.cerchio]]
text = "Che il tuo sentiero sia sempre soleggiato e torni presto a passare di qui"
[[frasi.cerchio]]
text = "Possa il tuo canto levarsi forte e gioioso come ora"

[[frasi.clan]]
author = "Lord Baden-Powell of Gilwell"
text = """Come Rover dovrai ricordare che, varcando le soglie dell'adolescenza verso la virilità, avrai superato lo
stadio in cui si impara ad osservare la Legge Scout ma che ormai dovrai applicarla praticamente
usandola come guida alla tua condotta nella vita. Per di più sei ora in situazione di responsabilità tale da
dare l'esempio agli altri, esempio che potrà condurre verso il bene e verso il male, a quanto a fondo tu
mantieni la Promessa che hai fatto sul tuo onore, come Rover, di offrire agli altri buona volontà ed
aiuto.
  """

[[frasi.coca]]
author = "Lord Baden-Powell of Gilwell"
text = """
Ogni uomo e donna che partecipano al nostro lavoro... compie un'opera
che tende sia nel principio che nei dettagli a umanizzare il mondo,
a rendere il più alto servizio contribuendo a compiere ciò che Dio ha chiesto,
il Suo regno di Pace e Buona volontà tra gli uomini.
"""

[[frasi.coca]]
author = "Lord Baden-Powell of Gilwell"
text = """
Il segreto di ogni sana educazione è di far sì che ogni allievo impari da sé,
invece di istruirlo convogliando dentro di lui una serie di nozioni...
Il metodo è quello di condurre il ragazzo ad affrontare l'obiettivo di fondo della sua formazione,
senza annoiarlo con troppi particolari.
"""

[[frasi.coca]]
author = "Lord Baden-Powell of Gilwell"
text = """
Il sistema migliore è far sì che i ragazzi imparino da soli
dando loro attività che li interessano,
anziché inculcar loro nozioni sotto forma arida e scheletrica istruzione.
Dobbiamo ricordarci che la grande maggioranza dei ragazzi
è già stanca per le ore passate in scuola o bottega
e che quindi la nostra attività deve essere sotto forma di ricreazione,
ed in quanto possibile all'aperto.
  """

[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "...vi terrete sempre pronti in spirito e corpo per compiere il vostro dovere..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Guida da te la tua canoa!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "...nessun profumo vale l'odore di quel fuoco..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Essere buoni è qualche cosa, fare il bene è molto meglio."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Un sorriso fa fare il doppio di strada di un brontolio!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Quando sei a corto di idee, risparmia il cervello e serviti delle orecchie..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Sforzati sempre di vedere ciò che splende dietro le nuvole più nere..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "'Andiamo', non 'vai', se vuoi che un lavoro sia fatto..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Gioca, non stare a guardare!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Gioca nella squadra di Dio!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Se sei un piolo quadrato, datti da fare per trovare un buco quadrato!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "...le stelle sono là, molto al di sopra dei comignoli delle case..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Un viso sveglio e sorridente rallegra coloro che lo incontrano..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Abituati a vedere le cose anche dal punto di vista dell'altro..."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "La capo che ci sa fare non spinge guida"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Ti è stato dato un corpo meraviglioso da trattare come opera e tempio di Dio!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Il vero modo di essere felici è quello di procurare la felicità agli altri"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Quando la strada non c'è, inventala!"
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Procurate di lasciare il mondo un po' migliore di come lo avete trovato."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Una difficoltà non è più tale una volta che ne abbiate riso e l'abbiate affrontata."
[[frasi.gruppo]]
author = "Lord Baden-Powell of Gilwell"
text = "Un colpetto sulla spalla è uno stimolo più efficace di una puntura di spillo."

[[frasi.noviziato]]
author = "Lord Baden-Powell of Gilwell"
text = """La Legge dei Rovers è la stessa degli Scouts nella lettera e nello spirito
ma deve essere considerata da un diverso punto di vista che è quello dell'uomo.
In entrambi i casi il principio fondamentale della Legge Scout
esclude risolutamente l'egoismo e spalanca la porta alla buona volontà
ed al servizio verso il prossimo.
"""

[[frasi.reparto]]
author = "Lord Baden-Powell of Gilwell"
text = """
Quando ero giovane c'era in voga una canzone popolare:
<Guida la tua canoa> con il ritornello>
<Non startene inerte triste o adirato
Da solo tu devi guidar la tua canoa>.
Questo era davvero un buon consiglio per la vita.
Nel disegno che ho fatto
sei tu che stai spingendo con la pagaia la canoa
non stai remando in una barca.
La differenza è che nel primo caso tu guardi dinnanzi a te
e vai sempre avanti mentre nel secondo non puoi guardare
dove vai e ti affidi al timone tenuto da altri e perciò
puoi cozzare contro qualche scoglio prima di rendertene conto.
Molta gente tenta di remare attraverso la vita in questo modo.
Altri ancora preferiscono imbarcarsi passivamente
veleggiando trasportati dal vento della fortuna o dalla corrente
del caso: è più facile che remare ma egualmente pericoloso.
Preferisco uno che guardi innanzi a sé e sappia condurre
la sua canoa cioè si apra da solo la propria strada.
Guida tu la tua canoa.
  """
