[cards]

[[cards.lupetti]]
text = """
Il lupetto pensa agli altri come a se stesso.
Il lupetto vive con gioia e lealtà insieme al branco.
"""
title = "La Legge"

[[cards.lupetti]]
text = """
Del Nostro Meglio
"""
title = "Il Motto"

[[cards.lupetti]]
text = """
Prometto, con l'aiuto e l'esempio di Gesù,
di fare del mio meglio
per migliorare me stesso,
per aiutare gli altri,
per osservare la legge del branco."""
title = "La Promessa"

[[cards.lupetti]]
text = """
Akela: buona caccia a tutti quelli che rispettano la legge della giungla.
Bagheera: zampe che non fanno rumore, occhi che vedono nell'oscurità, orecchi che odono il vento delle tane e denti bianchi e taglienti.
Baloo: la giungla è grande e il pupo è piccolino, che taccia e ascolti.
Kaa: cuor leale e lingua cortese fanno strada nella giungla.
Popolo Cacciatore: siamo dello stesso sangue fratellino tu ed io."""
title = "Le Parole Maestre"

[[cards.lupetti]]
text = """
I lupetti salutano con la mano destra, portando l'indice e il medio tesi e divaricati all'altezza della tempia, l'anulare ed il mignolo ripiegati sotto il pollice.
Le due dita divaricate ricordano i due articoli della Legge e le orecchie tese del lupo, mentre il pollice che copre le prime falangi dell'anulare e del mignolo rappresenta il più grande che protegge il più piccoli."""
title = "Il Saluto del Lupetto"

[[cards.lupetti]]
text = """
Tutti i Lupetti e i Vecchi Lupisono in cerchio. Akela sceglie il lupo che guiderà il grande urlo.
Akela grida: «Pronti per il Grande»
Tutti: «URLO!»
A questo punto il Branco spiccherà un piccolo saltello accucciandosi poi a terra sulle punte sollevando i talloni, mani con le due dita indice e medio chiuse unite in mezzo alle gambe.
Il lupo più anziano grida facendo un urlo:  «Aaa-»,
e subito tutto il branco lo segue gridando: «ke-la! Deeel nooostrooo MEGLIO!»
A questo punto tutti saltano in piedi e salutano a due mani con le due dita indice e medio chiuse unite avvicinate ai lati della testa e rivolte verso l'alto, a somigliare le due orecchie del lupo.
Ora il lupetto che guida il grande urlo grida al branco voltandosi prima  a destra e poi a sinistra. «Vostro meglio, vostro meglio! Vostro meglio, vostro meglio!»
Ora tutti abbassano il braccio sinistro e nella posizione di saluto, con le due dita aperte rispondono: «Siii! Meglio, meglio, meglio, meglio.»"""
title = "Il Grande Urlo"

[[cards.lupetti]]
text = """
I lupetti salutano con la mano destra, portando l'indice e il medio tesi e divaricati all'altezza della tempia, l'anulare ed il mignolo ripiegati sotto il pollice.
Le due dita divaricate ricordano i due articoli della Legge e le orecchie tese del lupo, mentre il pollice che copre le prime falangi dell'anulare e del mignolo rappresenta il più grande che protegge il più piccoli."""
title = "Il Saluto del Lupetto"

[[cards.lupetti]]
text = """
Buon Gesù,
ti amo con tutto il cuore perchè mai troverò miglior amico di te.
Per farti piacere io voglio, per tutta la giornata, con l'aiuto di Maria nostra mamma del cielo, fare del mio meglio come tu facesti un giorno a Nazareth.
Insegnami dunque ad ascoltare non me stesso, ma la tua voce, quella dei miei genitori, dei miei superiori, dei miei capi.
Amen"""
title = "La Preghiera del Lupetto"

